---
#
# Playbook to install the wordpress stack 
#

- name: Install wordpress stack on wordpress machine
  hosts: wordpress
  remote_user: vagrant
  become: true
  roles:
  - { role: MySQL }
  - { role: apache }
  - { role: filebeat }
  - { role: php }
  - { role: wordpress }



